plugins {
    id 'java'
    id 'application'
    id 'jacoco'
    id 'com.diffplug.spotless' version '6.25.0'
}

application {
    mainClass = project.findProperty('mainClass') ?: 'crm.work.App'
}

run {
    standardInput = System.in
}

group = 'crm.work'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.postgresql:postgresql:42.7.4'
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacoco {
    toolVersion = '0.8.13'
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = true
        html.required = true
    }
}

spotless {
    java {
        target 'src/**/*.java'
        googleJavaFormat('1.23.0')
        removeUnusedImports()
        trimTrailingWhitespace()
        endWithNewline()
    }
}