FROM eclipse-temurin:21-jdk AS build
WORKDIR /src
COPY src/main/java/ru/mentee/power/mcloud_6/NumberGuessGame.java .
RUN javac -d out NumberGuessGame.java

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /src/out/ .
CMD ["java", "ru.mentee.power.mcloud_6.NumberGuessGame"]
