apiVersion: v1
kind: Service
metadata:
  name: configurable-calculator
  namespace: mcloud-13
spec:
  selector:
    app: configurable-calculator
  ports:
    - port: 8080
      targetPort: 8080
      name: http
